#!/usr/bin/env bash
# script that transfers file from my client to server
# uses scp command with no strict host key checking

if [ $# -lt 4 ];
then
    echo 'Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY'
    exit 1
fi
scp -i $4 -o StrictHostKeyChecking=no $1 $3@$2:~/$1
