#!/usr/bin/env bash
# Script to query nginx web server w/ get request using curl-returns web page
# Completed in own virtual server

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
sudo service nginx start
