#!/usr/bin/env bash
# Script that configures nginx server to redirect user

sudo apt-get -y update
sudo apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com permanent;" /etc/nginx/sites-available/default
sudo service nginx start
