#!/usr/bin/env bash
# Script to configure web-02 to be identical to web-01
# and adds custom Nginx response header
#shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

server_config=\
"server {
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;
	server_name _;
	add_header X-Served-By \$hostname;
	
	location / {
		try_files \$uri \$uri/ =404;
	}
	if (\$request_filename ~ redirect_me){
		rewrite ^ https://youtube.com/watch?v=QH2-TGUlwu4 permanent;
	}
	error_page 404 /404.html;
	location = /404.html {
		internal;
	}
}"
#sudo sed -i "/listen 80 default_server/i add_header X-Served_By $HOSTNAME;" /etc/nginx/sites-available/default

sudo service nginx start
