#!/usr/bin/env bash
# Script to configure web-02 to be identical to web-01
# and adds custom Nginx response header
#shellcheck disable=SC2154

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/www/html/index.html
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html

str_add="http {\n\tadd_header X-Served-By \"$HOSTNAME\";"
sudo sed -i "s/http {/$str_addg/" /etc/nginx/nginx.conf

#str_replace="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.google.com permanent;\n\tadd_header X-Served-By \$HOSTNAME;"
#sudo sed -i "s/server_name _;/$str_replace/" /etc/nginx/sites-enabled/default

#str_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
#sudo sed -i "s/listen 80 default_server;/$str_replace/" /etc/nginx/sites-enabled/default

sudo service nginx start
