#!/usr/bin/env bash
# Script configures haproxy on server using roundrobin algorithm

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.5
sudo apt-get update -y
sudo apt-get install -y haproxy

echo \
	"
frontend haproxy
	bind *:80
	default_backend servers

backend servers
	balance roundrobin
	server 277341-web-01 100.25.132.50
	server 277341-web-02 34.234.204.29
" >> /etc/haproxy/haproxy.cfg
service haproxy restart
