#!/usr/bin/env bash
# Script configures haproxy on server using roundrobin algorithm

sudo apt-get install -y --no-install-recommends software-properties-common
sudo add-apt-repository -y ppa:vbernat/haproxy-2.4
sudo apt-get update -y
sudo apt-get install -y haproxy

load_balncer="\
frontend haproxy
	bind *:80
	mode http
	default_backend webservers
backend webservers
	mode http
	balance roundrobin
	server 27734-web-01 100.25.132.50 check
	server 277341-web-02 34.234.204.29 check
"
echo '$load_balancer' >> /etc/haproxy/haproxy.cfg
service haproxy restart
