#!/usr/bin/env bash
# Generates mysql dump and creates compressed archive from it

date=$(date +"%d-%m-%Y")

mysqldump --all-databases -u root --password="$1" > backup.sql

tar -czvf "$date.tar.gz" backup.sql
