#!/usr/bin/env bash
# Displays 'To infinity and beyond' but 'I am invincible' when 
# SIGTERM signal is sent

while true
do
	echo 'To infinity and beyond'
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
