#!/usr/bin/env bash
# This script displays text 10 times,but 9th iteration 'Hi'

counter=1

while [ $counter -le 10 ]
do
	if [ $counter -eq 9 ]
	then
        	echo 'Best School'
		echo 'Hi'
	else
		echo 'Best School'
        fi
	((counter++))
done
