#!/usr/bin/env bash
# Loops from 1-10 printing different text on diff iterations

counter=1
while [ $counter -le 10 ]
do
    if [ $counter == '4' ]
    then
        echo 'bad luck'
    elif [ $counter == '8' ]
    then
        echo 'good luck'
    else
        echo 'Best School'
    fi
    ((counter++))
done
