#!/usr/bin/env bash
# Script gives information about the 'school' file, if exists or not

FILENAME="school"
if [[ -e "$FILENAME" ]]
then
    echo "$FILENAME file exists"
    if [ -s "$FILENAME" ]
    then
        echo "$FILENAME file is not empty"
    else
        echo "$FILENAME file is empty"
    fi
    if [ -f "$FILENAME" ]
    then
        echo "$FILENAME is a regular file"
    fi
else
    echo "$FILENAME file does not exist"
fi
