#!/usr/bin/env bash
# Fixes web server to run nginx as nginx user listening on port 8080

sed -i "s/user www-data;/user nginx;/" /etc/nginx/nginx.conf
sed -i "/listen 80;/a\    listen 8080;" /etc/nginx/sites-available/default
chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
